from typing import Dict, List


DOMAIN_TEMPLATES: Dict[str, List[str]] = {
    "ecommerce": [
        "User Authentication & Authorization (OAuth2, JWT, role-based access, social login, session management, password reset, email verification)",
        "Product Catalog Management (CRUD operations, categories & subcategories, product variants/SKUs, inventory tracking, bulk import/export, image management, SEO metadata)",
        "Shopping Cart & Session Management (persistent cart, guest checkout, cart recovery, quantity management, price calculation, tax estimation)",
        "Order Management System (order processing pipeline, status tracking, order history, cancellations, returns/exchanges, invoice generation, shipping label integration)",
        "Payment Gateway Integration (Stripe/PayPal/Razorpay, webhook handling, refunds & partial refunds, retry logic, PCI compliance, multi-currency support, saved payment methods)",
        "Admin Dashboard (sales analytics, revenue reports, user management, product management, inventory alerts, order monitoring, coupon/discount management)",
        "Search & Filtering (full-text product search, faceted filters, sorting options, autocomplete/typeahead, search analytics, recently viewed products)",
        "Customer Profile Management (multiple addresses, wishlists, saved payment methods, order history, preferences, loyalty points tracking)",
        "Email & Notification System (order confirmations, shipping updates, delivery notifications, abandoned cart reminders, promotional emails, SMS notifications, push notifications)",
        "Review & Rating System (product reviews, star ratings, image uploads, verified purchase badges, review moderation, helpful votes, Q&A section)",
        "Coupon & Promotion Engine (percentage/flat discounts, promo codes, flash sales, bundle deals, free shipping rules, usage limits, auto-apply rules)",
        "Shipping & Logistics Integration (carrier APIs, rate calculation, tracking integration, multi-warehouse support, delivery slot selection, return shipping labels)",
    ],

    "saas": [
        "User Authentication & Authorization (SSO via SAML/OIDC, MFA/2FA, RBAC with granular permissions, API key management, session management, password policies, IP whitelisting)",
        "Multi-tenant Architecture (tenant isolation strategies, data segregation, tenant-specific configurations, subdomain/custom domain routing, resource quotas per tenant, tenant provisioning/deprovisioning)",
        "Subscription & Billing Management (tiered plans, usage-based billing, invoicing, payment processing, proration, trial management, plan upgrades/downgrades, dunning management, tax calculation, revenue recognition)",
        "Admin Dashboard (tenant management, system-wide analytics, resource monitoring, feature flag management, support ticket overview, system health metrics, deployment status)",
        "User Management (invitation flows, role assignment, team/organization hierarchy, permission groups, user deactivation/suspension, SCIM provisioning, seat management)",
        "API Gateway & Rate Limiting (RESTful/GraphQL API, versioning, rate limiting per plan tier, API key authentication, usage tracking, throttling, request/response logging, SDK generation)",
        "Audit Logging & Activity Tracking (user activity logs, admin action logs, data change history, exportable audit reports, retention policies, compliance-ready logging, login history)",
        "Email & Notification System (transactional emails, in-app notifications, webhook notifications, notification preferences, digest emails, Slack/Teams integrations, custom notification channels)",
        "Onboarding Flow & User Setup (interactive product tours, setup wizards, checklist-based onboarding, sample data seeding, getting started guides, contextual tooltips, progress tracking)",
        "Settings & Configuration Management (tenant-level settings, user preferences, branding/white-labeling, custom fields, feature toggles, integration configuration, data export/import settings)",
        "Analytics & Reporting (usage analytics, custom report builder, scheduled reports, data export, dashboard widgets, funnel analysis, cohort tracking)",
        "Workspace & Collaboration (shared workspaces, real-time collaboration, comments/mentions, activity feeds, file sharing, role-based content visibility)",
    ],

    "marketplace": [
        "User Authentication & Authorization (buyer/seller/admin role separation, social login, email verification, seller identity verification, account linking)",
        "Vendor/Seller Onboarding & Management (registration workflow, document verification, KYC/KYB checks, seller agreement acceptance, profile setup wizard, seller tier/level system, performance scoring)",
        "Product Listing Management (multi-vendor catalog, listing approval workflow, bulk upload, category mapping, listing templates, quality guidelines enforcement, duplicate detection, listing analytics)",
        "Search & Discovery (advanced faceted filters, recommendation engine, trending/featured products, personalized suggestions, saved searches, location-based results, price comparison, autocomplete)",
        "Order Management (split orders across vendors, vendor routing, fulfillment tracking per vendor, partial cancellations, returns per vendor, dispute-initiated refunds, automated order allocation)",
        "Payment Processing (split payments to vendors, escrow holding, commission deduction, automated payouts, refund handling, multi-currency support, payment dispute management, tax withholding)",
        "Review & Rating System (buyer reviews for products, buyer reviews for sellers, seller reviews for buyers, review moderation queue, photo/video reviews, review response by seller, trust score calculation)",
        "Admin Dashboard (vendor approval queue, dispute resolution center, platform analytics, commission reports, flagged content review, marketplace health metrics, category management, featured listing management)",
        "Messaging System (buyer-seller communication, order-linked conversations, file attachments, automated responses, message templates, conversation archival, abuse reporting, admin monitoring)",
        "Commission & Payout Management (configurable commission rates per category/vendor, payout scheduling, minimum payout thresholds, payout methods, transaction fee handling, commission reports, tax document generation)",
        "Dispute & Resolution Center (dispute filing, evidence submission, escalation workflow, admin mediation, automated resolution rules, refund/compensation processing, dispute analytics)",
        "Vendor Analytics Dashboard (sales reports, traffic analytics, inventory alerts, competitor insights, performance metrics, payout history, customer demographics)",
    ],

    "healthcare": [
        "User Authentication & Authorization (patient/provider/admin/staff roles, MFA, session timeout policies, emergency access override, biometric login, proxy/guardian access, audit-ready authentication)",
        "Patient Management System (demographics, medical history, insurance information, emergency contacts, consent management, patient portal, family/dependent linking, patient merge/dedup)",
        "Appointment Scheduling & Calendar Management (provider availability, appointment types, recurring appointments, waitlist management, auto-reminders, buffer time, multi-location scheduling, online self-scheduling, cancellation/rescheduling policies)",
        "Electronic Health Records (EHR) Management (clinical notes, lab results, imaging records, medication history, allergy tracking, vital signs tracking, document upload, structured data entry, template-based charting, interoperability via HL7/FHIR)",
        "Provider/Doctor Management (profiles, credentials/certifications, specialty tagging, availability management, referral network, panel management, performance metrics, license verification tracking)",
        "Prescription Management System (e-prescribing, medication database, drug interaction checking, dosage calculators, refill management, pharmacy integration, controlled substance handling, prescription history)",
        "Billing & Insurance Processing (claims submission, eligibility verification, copay/deductible calculation, EOB processing, patient billing, payment plans, coding assistance ICD-10/CPT, denial management, superbill generation)",
        "Admin Dashboard (practice analytics, compliance reporting, user management, resource utilization, financial overview, population health metrics, staff scheduling overview, regulatory deadline tracking)",
        "HIPAA Compliance Features (end-to-end encryption, comprehensive audit logs, access controls, BAA management, data retention policies, breach notification workflows, minimum necessary access, de-identification tools, security risk assessments)",
        "Notification System (appointment reminders via SMS/email/voice, lab result alerts, medication reminders, care plan notifications, provider-to-patient messaging, broadcast notifications, no-show follow-ups)",
        "Telemedicine Integration (video consultations, waiting room, screen sharing, in-session chat, file sharing, e-prescribing post-visit, visit recording with consent, technical readiness check, multi-participant sessions)",
        "Care Coordination (referral management, care team assignment, task management, care plan tracking, transitions of care, provider-to-provider messaging, shared care plans)",
    ],

    "fintech": [
        "User Authentication & Authorization (KYC verification tiers, MFA with authenticator/SMS/biometric, device fingerprinting, session management, suspicious login detection, IP geolocation checks, step-up authentication for high-risk actions)",
        "Account Management (user profiles, multi-level verification, linked accounts, beneficiary management, account statements, account freeze/unfreeze, account closure workflow, nominee management)",
        "Transaction Processing Engine (real-time processing, idempotency guarantees, double-entry bookkeeping, atomic operations, retry with backoff, dead letter queues, transaction limits enforcement, batch processing, scheduled transactions)",
        "Payment Gateway Integration (multi-provider support with fallback routing, smart routing, 3D Secure, tokenized payments, recurring payments, international payments, currency conversion, payment method management)",
        "Wallet & Balance Management (multi-currency wallets, real-time balance updates, hold/release mechanisms, minimum balance enforcement, wallet-to-wallet transfers, auto-top-up rules, balance snapshots, ledger reconciliation)",
        "Transaction History & Reporting (searchable transaction logs, categorization, downloadable statements, tax reports, spending analytics, custom date range filters, CSV/PDF export, graphical summaries)",
        "Admin Dashboard (real-time fraud monitoring, compliance dashboard, transaction analytics, user verification queue, suspicious activity alerts, system health monitoring, regulatory reporting, customer support tools)",
        "Compliance & Regulatory Features (AML screening, KYC/KYB workflows, sanctions list checking, PEP screening, transaction monitoring rules, CTR/SAR filing, regulatory reporting, license management, geographic restrictions)",
        "Security Features (end-to-end encryption, field-level encryption, tokenization of sensitive data, fraud detection ML models, velocity checks, device binding, IP blacklisting, security event alerting, penetration testing integration)",
        "Notification System (real-time transaction alerts, security notifications, OTP delivery, low balance warnings, payment reminders, promotional communications, regulatory notices, multi-channel delivery)",
        "Reconciliation & Settlement System (automated reconciliation, discrepancy detection, settlement scheduling, partner/bank reconciliation, exception handling, reconciliation reports, multi-entity settlement, end-of-day processing)",
        "Dispute & Chargeback Management (dispute filing, evidence collection, chargeback handling, provisional credits, resolution tracking, representment workflow, dispute analytics, regulatory timeline compliance)",
    ],

    "edtech": [
        "User Authentication & Authorization (student/instructor/admin/parent roles, SSO for institutions, LTI integration, age-appropriate verification, guardian-linked accounts, class-based access)",
        "Course Management System (course creation, curriculum builder, module/lesson organization, content versioning, prerequisite chains, course cloning, draft/publish workflow, collaborative authoring)",
        "Content Delivery & Management (video streaming with adaptive bitrate, document viewer, interactive content, SCORM/xAPI compliance, offline access/download, DRM protection, multimedia uploads, content CDN)",
        "Assessment & Examination Engine (quiz/test builder, question banks, randomization, auto-grading, manual grading workflows, rubrics, proctoring integration, timed assessments, plagiarism detection, grade book)",
        "Student Progress Tracking (learning analytics, completion tracking, grade history, skill mapping, learning path visualization, performance trends, at-risk student alerts, time-spent analytics)",
        "Live Classes & Virtual Classroom (video conferencing, whiteboard, screen sharing, breakout rooms, hand raising, polls/quizzes, attendance tracking, recording, chat moderation)",
        "Discussion & Collaboration (discussion forums, peer review, group projects, study groups, Q&A boards, threaded discussions, instructor announcements, file sharing)",
        "Admin Dashboard (enrollment analytics, instructor performance, course completion rates, revenue reports, student engagement metrics, institution management, compliance reporting)",
        "Certificate & Credentialing (certificate generation, digital badges, blockchain verification, credential sharing, completion criteria, certificate templates, transcript generation)",
        "Payment & Enrollment (course purchasing, subscription plans, coupon codes, installment payments, institutional licensing, bulk enrollment, refund management, financial aid integration)",
        "Notification & Communication System (assignment reminders, grade notifications, course announcements, deadline alerts, parent notifications, instructor messaging, push/email/SMS delivery)",
        "Gamification & Engagement (points/XP system, leaderboards, streaks, achievements/badges, learning challenges, peer competition, progress milestones)",
    ],

    "logistics": [
        "User Authentication & Authorization (shipper/carrier/driver/warehouse/admin roles, multi-organization access, API key management for partners, location-based access restrictions)",
        "Shipment Management (shipment creation, booking, pickup scheduling, multi-leg routing, consolidation/deconsolidation, cross-docking, freight class assignment, shipment lifecycle tracking)",
        "Real-time Tracking & Visibility (GPS tracking, geofencing, milestone-based tracking, ETA calculation, live map view, IoT sensor integration, chain of custody, proof of delivery, customer-facing tracking portal)",
        "Route Optimization (multi-stop routing, dynamic rerouting, traffic/weather integration, fuel cost optimization, driver hours compliance, capacity utilization, time window constraints, load optimization)",
        "Warehouse Management (inventory receiving, putaway, pick/pack/ship, stock counts, bin/location management, wave planning, cross-dock management, returns processing, barcode/RFID integration)",
        "Fleet Management (vehicle registry, maintenance scheduling, fuel tracking, driver assignment, compliance documentation, vehicle inspection logs, utilization reports, telematics integration)",
        "Order & Fulfillment Management (order ingestion, allocation rules, fulfillment prioritization, split shipment handling, backorder management, drop-ship coordination, SLA tracking)",
        "Carrier & Rate Management (carrier onboarding, rate cards, rate shopping, contract management, carrier performance scoring, lane analysis, spot quoting, carrier compliance verification)",
        "Admin Dashboard (operational KPIs, shipment volume analytics, on-time delivery metrics, cost analysis, exception monitoring, capacity planning, customer performance reports)",
        "Billing & Invoicing (freight billing, accessorial charges, rate auditing, invoice reconciliation, customer billing, carrier payment, dispute management, cost allocation)",
        "Document Management (BOL generation, customs documentation, commercial invoices, packing lists, certificates of origin, digital signature, document archival, regulatory document compliance)",
        "Notification & Alert System (shipment status updates, exception alerts, delivery notifications, driver notifications, weather/disruption alerts, SLA breach warnings, customer communication)",
    ],

    "crm": [
        "User Authentication & Authorization (sales rep/manager/admin roles, territory-based access, team hierarchy, SSO, data visibility rules, field-level security)",
        "Contact & Account Management (contact records, company/account profiles, relationship mapping, contact deduplication, import/export, custom fields, contact scoring, organizational hierarchy, merge/unmerge)",
        "Lead Management (lead capture from multiple sources, lead scoring/grading, lead assignment rules, lead nurturing workflows, qualification criteria, lead conversion, source tracking, duplicate detection)",
        "Sales Pipeline & Opportunity Management (customizable pipeline stages, deal tracking, probability/forecasting, weighted pipeline, multi-pipeline support, deal rotation, win/loss analysis, stage duration tracking, pipeline velocity metrics)",
        "Activity Tracking & Communication (email tracking with open/click, call logging, meeting scheduling, task management, activity timeline, email templates, sequence/cadence automation, calendar integration, communication history)",
        "Reporting & Analytics (sales dashboards, pipeline reports, forecast reports, activity reports, custom report builder, scheduled reports, goal tracking, trend analysis, team performance comparison, export capabilities)",
        "Admin Dashboard (user management, system configuration, data quality monitoring, adoption metrics, integration health, storage usage, bulk operations, data governance)",
        "Workflow & Automation (trigger-based automation, approval workflows, task auto-assignment, follow-up reminders, field update rules, escalation rules, SLA enforcement, automated email sequences)",
        "Email & Communication Integration (email sync, inbox integration, email templates, mass email, email scheduling, tracking pixels, unsubscribe management, deliverability monitoring, shared inbox)",
        "Document & Proposal Management (proposal generation, document templates, e-signature integration, document tracking, version control, content library, CPQ integration)",
        "Integration Hub (REST API, webhook support, native integrations with email/calendar/phone, marketing automation sync, ERP integration, data sync rules, field mapping, error handling)",
        "Territory & Quota Management (territory definition, assignment rules, quota setting, quota attainment tracking, territory rebalancing, coverage analysis, capacity planning)",
    ],

    "hrms": [
        "User Authentication & Authorization (employee/manager/HR/admin/executive roles, org-hierarchy-based access, SSO, self-service portal, delegate access, data privacy controls)",
        "Employee Information Management (personal details, employment history, documents, org chart, custom fields, employee directory, data change requests, bulk updates, employee lifecycle events)",
        "Recruitment & Applicant Tracking (job posting, application management, resume parsing, interview scheduling, evaluation scorecards, offer management, background check integration, careers page, referral tracking, pipeline analytics)",
        "Onboarding & Offboarding (onboarding checklists, document collection, equipment provisioning, buddy assignment, task workflows, exit interviews, knowledge transfer, asset recovery, offboarding checklist, alumni management)",
        "Leave & Attendance Management (leave policies, leave requests/approvals, leave balance tracking, holiday calendar, attendance tracking, timesheet management, shift scheduling, overtime calculation, geo-fenced attendance, biometric integration)",
        "Payroll Processing (salary computation, tax calculations, statutory deductions, reimbursements, payslip generation, bank file generation, multi-country payroll, arrears processing, year-end processing, compliance reporting)",
        "Performance Management (goal setting, OKR/KPI tracking, self/peer/manager reviews, 360-degree feedback, competency mapping, performance improvement plans, calibration sessions, continuous feedback, rating scales, promotion recommendations)",
        "Learning & Development (training catalog, course enrollment, skill gap analysis, learning paths, certification tracking, training calendar, budget tracking, vendor management, post-training assessments, compliance training)",
        "Benefits Administration (benefit plan management, open enrollment, life event changes, benefit eligibility rules, provider integration, employee self-service, cost modeling, COBRA management, dependent management)",
        "Admin Dashboard (headcount analytics, attrition analysis, diversity metrics, compensation analysis, compliance monitoring, org health metrics, cost center reporting, workforce planning, benchmark data)",
        "Employee Self-Service Portal (profile updates, document access, payslip viewing, leave applications, expense claims, help desk tickets, benefits enrollment, training enrollment, feedback submission)",
        "Compliance & Document Management (labor law compliance, mandatory training tracking, document generation, e-signatures, policy acknowledgments, audit trail, data retention, regulatory reporting, work permit tracking)",
    ],

    "real_estate": [
        "User Authentication & Authorization (buyer/seller/agent/broker/admin roles, agency hierarchy, license verification, territory-based access, client data privacy controls)",
        "Property Listing Management (listing creation with rich media, property details/specifications, MLS integration, listing syndication, virtual tours/3D walkthroughs, floor plans, listing status lifecycle, comparable market analysis)",
        "Property Search & Discovery (map-based search, advanced filters, saved searches, search alerts, neighborhood info, school data, commute calculator, nearby amenities, mortgage calculator, price history)",
        "Lead & Client Management (inquiry capture, lead assignment, client communication tracking, viewing history, saved properties, client requirements matching, follow-up automation, client portal)",
        "Showing & Appointment Management (viewing scheduling, availability management, tour routing, lockbox/access coordination, feedback collection, automated follow-ups, open house management, virtual showing support)",
        "Transaction Management (offer submission, negotiation tracking, document management, contract generation, e-signatures, milestone tracking, closing checklist, escrow coordination, title integration, commission split calculation)",
        "Agent & Broker Dashboard (listing performance, lead pipeline, commission tracking, activity reports, market analytics, team performance, goal tracking, GCI reporting)",
        "Admin Dashboard (office management, agent onboarding, brokerage analytics, compliance monitoring, MLS sync status, listing quality metrics, revenue reporting, market share analysis)",
        "Document Management (contract templates, addendum library, disclosure forms, e-signature workflows, document vault, version tracking, compliance document collection, automated document generation)",
        "Marketing & Communication (email campaigns, property brochures, social media integration, CMA reports, market update newsletters, automated drip campaigns, open house promotion, IDX website integration)",
        "Payment & Commission Management (commission plans, split configurations, referral fee tracking, closing disbursement, agent billing, brokerage fees, transaction fee management, payment history)",
        "Rental & Property Management (lease management, rent collection, maintenance requests, tenant screening, lease renewal automation, property inspection scheduling, expense tracking, owner reporting)",
    ],

    "project_management": [
        "User Authentication & Authorization (team member/project manager/admin/client roles, workspace-based access, SSO, guest access, project-level permissions, IP restrictions)",
        "Project & Workspace Management (project creation, templates, project hierarchy, portfolio management, project archival, project cloning, status dashboards, project categorization/tagging)",
        "Task Management (task creation, subtasks, dependencies, assignments, due dates, priority levels, custom fields, recurring tasks, task templates, bulk operations, drag-and-drop ordering, checklist items)",
        "Views & Visualization (Kanban boards, Gantt charts, timeline view, calendar view, table/list view, workload view, mind map, custom views, filtered views, saved views)",
        "Sprint & Agile Management (sprint planning, backlog grooming, story points, velocity tracking, burndown/burnup charts, sprint retrospectives, release planning, epic management, agile board customization)",
        "Time Tracking & Resource Management (time logging, timesheets, billable/non-billable hours, resource allocation, capacity planning, utilization reports, time estimates vs actuals, approval workflows)",
        "Collaboration & Communication (comments/discussions, @mentions, file attachments, activity feed, real-time updates, document collaboration, shared notes, meeting notes, status updates, proofing/annotation)",
        "Reporting & Analytics (project health dashboards, progress reports, team performance, time reports, custom report builder, scheduled reports, portfolio analytics, burndown charts, resource utilization, client reports)",
        "Admin Dashboard (workspace management, user management, billing/plan management, integration settings, security settings, audit logs, usage analytics, template management, custom field management)",
        "Integration & Automation (webhook support, REST API, native integrations, custom automation rules, trigger-action workflows, Zapier/Make integration, import/export, email-to-task, form-to-task)",
        "Document & Knowledge Management (project wiki, document storage, templates, version history, linked documents, shared folders, search across documents, embeddable docs in tasks)",
        "Client & Stakeholder Portal (client access with limited views, approval workflows, feedback collection, progress visibility, invoice sharing, deliverable submission, guest commenting)",
    ],

    "social_media_platform": [
        "User Authentication & Authorization (email/phone/social signup, MFA, account verification/badges, age verification, account recovery, device management, login activity monitoring)",
        "User Profile Management (profile creation, bio/avatar/cover, privacy settings, profile customization, linked accounts, follower/following lists, profile analytics, verification applications)",
        "Content Creation & Publishing (text/image/video/audio posts, rich text editor, media upload/compression, content scheduling, drafts, content tagging, location tagging, alt text, carousel/gallery posts, stories/ephemeral content)",
        "Social Graph & Discovery (follow/friend system, suggested connections, mutual connections, people search, trending topics, explore/discover feed, hashtag system, topic-based recommendations)",
        "Feed & Content Algorithm (personalized feed, chronological option, algorithmic ranking, content diversity, engagement signals, content freshness, follow-based vs interest-based, feed preferences)",
        "Engagement Features (likes/reactions, comments/replies, shares/reposts, bookmarks/saves, polls, Q&A, live streaming, direct messaging, group messaging, read receipts, typing indicators)",
        "Content Moderation (automated content screening, report system, human review queue, appeal process, community guidelines enforcement, spam detection, NSFW filtering, shadow ban, content warnings, trust & safety dashboard)",
        "Notification System (push/email/in-app, notification preferences, digest mode, mention notifications, engagement notifications, follower notifications, smart grouping, do-not-disturb scheduling)",
        "Admin Dashboard (user management, content moderation queue, platform analytics, reported content review, trend monitoring, system health, feature flag management, A/B testing, policy enforcement)",
        "Monetization & Creator Tools (creator fund, tipping/donations, paid subscriptions, branded content tools, affiliate linking, analytics dashboard, payout management, sponsorship marketplace)",
        "Privacy & Safety (block/mute, privacy settings, data download, account deactivation/deletion, two-factor authentication, login alerts, restricted accounts, close friends/circles, hidden words filter)",
        "Search & Trending (full-text search, hashtag search, user search, trending topics, location-based trending, search history, search suggestions, saved searches)",
    ],

    "food_delivery": [
        "User Authentication & Authorization (customer/restaurant/driver/admin roles, phone/email verification, social login, multi-device session management, restaurant owner verification)",
        "Restaurant & Menu Management (restaurant onboarding, menu builder, item customization/modifiers, pricing management, availability/hours management, menu categories, photos, nutritional info, prep time, item pause/unpause)",
        "Customer Ordering (restaurant browsing, menu viewing, cart management, item customization, special instructions, group ordering, reorder from history, scheduled orders, address management, delivery/pickup toggle)",
        "Search & Discovery (restaurant search, cuisine filters, dietary filters, rating/price sorting, location-based results, featured/promoted restaurants, deals/offers section, personalized recommendations, recently ordered)",
        "Order Processing & Management (order placement, restaurant acceptance/rejection, prep time management, order queue, real-time status updates, order modification window, cancellation handling, refund processing, partial fulfillment)",
        "Driver/Delivery Management (driver onboarding, real-time assignment, route optimization, delivery tracking, batch delivery, driver availability management, earnings dashboard, delivery proof, driver rating system, shift management)",
        "Real-time Tracking (live map tracking, ETA updates, driver location sharing, order status milestones, push notification updates, delivery geofencing, photo proof of delivery)",
        "Payment Processing (multiple payment methods, split payments, wallet/credits, tip management, promo codes/coupons, loyalty rewards, restaurant settlement, driver payout, surge pricing, refund processing)",
        "Review & Rating System (restaurant ratings, food item ratings, driver ratings, photo reviews, restaurant responses, review moderation, featured reviews, rating aggregation)",
        "Admin Dashboard (order analytics, restaurant performance, driver performance, customer metrics, revenue reports, operational metrics, zone management, surge/demand monitoring, dispute resolution, marketing campaign management)",
        "Notification System (order confirmation, status updates, driver assignment, delivery ETA, promotional notifications, restaurant alerts, driver notifications, rating reminders, deal alerts)",
        "Promotions & Loyalty (coupon management, referral programs, loyalty points, restaurant deals, platform-wide promotions, first-order discounts, free delivery campaigns, cashback offers, subscription programs)",
    ],

    "travel_booking": [
        "User Authentication & Authorization (traveler/host/agent/admin roles, social login, loyalty program integration, multi-currency preferences, corporate account management, travel agent access)",
        "Accommodation Search & Booking (property search, map-based browsing, date/guest filters, amenity filters, price comparison, instant booking, request-to-book, property details with photos/360-views, room type selection, dynamic pricing display)",
        "Flight Search & Booking (multi-city/round-trip/one-way, airline aggregation, seat selection, baggage options, fare class comparison, flight tracking, layover management, fare alerts, flexible date search, price calendar)",
        "Activity & Experience Booking (tours, activities, attraction tickets, experience search, availability calendar, group booking, gift booking, instant confirmation, cancellation flexibility)",
        "Itinerary Management (trip planner, multi-segment itinerary, shared itineraries, calendar integration, offline access, destination guides, booking consolidation, travel documents storage, trip timeline)",
        "Payment Processing (multi-currency support, split payments, installment plans, travel credits, refund processing, booking modifications, price guarantees, payment method management, corporate billing, invoice generation)",
        "Review & Rating System (property reviews, experience reviews, host ratings, photo reviews, verified stay badges, review response management, aggregated scores, review filtering)",
        "Host/Property Management (listing creation, calendar management, pricing rules, booking acceptance, guest communication, property photos, amenity management, check-in instructions, cleaning scheduling, co-host access, revenue reports)",
        "Admin Dashboard (booking analytics, revenue reports, property approval queue, dispute resolution, platform health metrics, geographic performance, conversion funnels, customer satisfaction metrics, partner management)",
        "Notification System (booking confirmations, price drop alerts, check-in reminders, travel advisories, review reminders, host/guest messaging, trip change notifications, loyalty program updates)",
        "Loyalty & Rewards Program (points accumulation, tier management, redemption options, partner benefits, status matching, anniversary rewards, referral bonuses, corporate rewards, points expiry management)",
        "Customer Support & Dispute Management (help center, live chat, booking modification requests, cancellation handling, refund processing, dispute resolution, emergency assistance, travel insurance claims)",
    ],

    "iot_platform": [
        "User Authentication & Authorization (device owner/operator/admin/integrator roles, API key management, OAuth2 for device authorization, certificate-based authentication, tenant isolation)",
        "Device Management (device registration, provisioning, configuration, firmware OTA updates, device grouping, device lifecycle management, device health monitoring, remote diagnostics, decommissioning, device templates/profiles)",
        "Data Ingestion & Processing (MQTT/CoAP/HTTP protocols, real-time streaming, message queuing, data normalization, time-series storage, batch processing, edge computing support, data compression, protocol translation)",
        "Dashboard & Visualization (real-time dashboards, custom widget builder, time-series charts, map-based visualization, device status overview, heatmaps, custom layouts, shared dashboards, embedded dashboards, mobile-responsive views)",
        "Alerting & Rule Engine (threshold-based alerts, complex event processing, rule builder, alert escalation, notification routing, alarm acknowledgment, alert history, predictive alerting, geofence triggers, multi-condition rules)",
        "Analytics & Reporting (historical data analysis, trend detection, anomaly detection, predictive maintenance, usage analytics, energy monitoring, custom reports, scheduled reports, data export, comparative analysis)",
        "API & Integration Management (REST/GraphQL APIs, webhook configuration, third-party integration marketplace, data export connectors, ERP/CRM integration, cloud platform bridges, custom protocol adapters)",
        "Admin Dashboard (fleet overview, system health, user management, billing/usage, tenant management, audit logs, resource monitoring, capacity planning, SLA monitoring, deployment management)",
        "Security & Compliance (end-to-end encryption, certificate management, access control lists, security audit logging, vulnerability scanning, compliance reporting, data residency controls, network segmentation, intrusion detection)",
        "Edge Computing Management (edge node deployment, edge rule configuration, local processing, edge-cloud sync, edge analytics, offline operation support, edge firmware management, distributed computing orchestration)",
    ],

    "insurance": [
        "User Authentication & Authorization (policyholder/agent/underwriter/claims adjuster/admin roles, MFA, SSO for enterprise, agency hierarchy, licensing verification, delegate access for beneficiaries)",
        "Policy Management (policy creation, quoting engine, underwriting workflow, policy issuance, endorsements/modifications, renewal management, cancellation/reinstatement, document generation, multi-line support, policy comparison)",
        "Claims Processing (FNOL submission, claims assessment, adjuster assignment, damage estimation, investigation workflow, settlement calculation, payment processing, subrogation tracking, SIU referral, claims timeline, document/photo upload)",
        "Customer Portal (policy overview, coverage details, ID card generation, claims filing, document upload, payment history, policy change requests, communication center, beneficiary management, coverage comparison tools)",
        "Underwriting Engine (risk assessment rules, automated underwriting, manual review queue, rating algorithms, third-party data integration, hazard analysis, coverage recommendations, exception handling, audit trail)",
        "Agent/Broker Management (agent onboarding, commission management, book of business, lead assignment, performance tracking, agency billing, appointment management, license tracking, CE credit monitoring, hierarchy management)",
        "Billing & Payments (premium calculation, installment plans, auto-pay enrollment, payment reminders, grace period management, lapse processing, reinstatement fees, commission disbursement, direct billing, agency billing)",
        "Admin Dashboard (portfolio analytics, loss ratio monitoring, claims pipeline, agent performance, underwriting metrics, regulatory compliance, reinsurance management, customer retention metrics, fraud indicators)",
        "Compliance & Regulatory (state/country regulatory compliance, rate filing management, form filing, policy form version control, regulatory reporting, data privacy, complaint management, audit trail, solvency reporting)",
        "Document Management (policy documents, claims documents, correspondence generation, template management, e-signatures, document indexing, retention policies, compliance documents, batch generation, mail merge)",
        "Notification & Communication System (policy reminders, renewal notices, claims status updates, payment reminders, agent notifications, regulatory notices, multi-channel delivery, communication preferences, audit trail)",
        "Analytics & Actuarial Reporting (loss analysis, reserve estimation, premium adequacy, risk segmentation, geographic analysis, trend identification, catastrophe modeling, reinsurance analysis, regulatory reporting)",
    ],

    "mobile_app": [
        "User Authentication (social login, biometric authentication, OAuth2, session management, password reset, email/phone verification)",
        "Push Notification System (FCM/APNs integration, scheduled notifications, rich media notifications, deep linking, notification preferences, silent notifications)",
        "Offline Mode & Data Sync (local storage, sync queue management, conflict resolution, background sync, offline-first architecture, delta sync)",
        "App Navigation & Routing (deep linking, tab navigation, stack navigation, gesture navigation, navigation state persistence, universal links)",
        "Device Features Integration (camera access, location services, contacts access, file system, biometric sensors, NFC, Bluetooth)",
        "App State Management (local persistence, caching strategies, session handling, app lifecycle management, state restoration)",
        "In-App Purchases & Subscriptions (Apple IAP, Google Play Billing, subscription management, receipt validation, restore purchases, promotional offers)",
        "Analytics & Crash Reporting (usage analytics, crash logs, performance monitoring, user journey tracking, A/B testing, session recording)",
        "App Settings & Preferences (user preferences, theme selection, language settings, notification settings, privacy controls, data management)",
        "Version Management & Updates (force update mechanism, soft update prompts, changelog display, app store links, feature flags, remote config)",
    ],

    "web_app": [
        "User Authentication (OAuth2, JWT, session management, MFA, password policies, social login, email verification, account recovery)",
        "Responsive Web Design (mobile-first approach, breakpoint management, touch support, PWA capabilities, responsive images, fluid layouts)",
        "Admin Dashboard (user management, content management, analytics dashboards, system settings, audit logs, role management)",
        "API Integration Layer (REST/GraphQL clients, error handling, retry logic, request caching, response transformation, API versioning)",
        "Search & Filtering (full-text search, faceted filters, sorting options, pagination, search suggestions, advanced search)",
        "Data Visualization (charts, graphs, tables, data export, interactive dashboards, real-time updates, custom reports)",
        "Notification System (email notifications, in-app notifications, browser push, notification center, preferences management, digest emails)",
        "Settings & Configuration (user preferences, account settings, privacy controls, profile management, connected accounts, data export)",
        "File Management (upload handling, storage integration, preview generation, download management, CDN integration, file type validation)",
        "SEO Optimization (meta tags, sitemap generation, structured data, performance optimization, social sharing, canonical URLs)",
    ],

    "ai_ml": [
        "User Authentication & API Key Management (OAuth2, API keys, usage quotas, rate limiting, team access, permission scopes)",
        "Data Pipeline Management (data ingestion, validation, transformation, versioning, quality checks, pipeline orchestration)",
        "Model Training Interface (experiment tracking, hyperparameter tuning, distributed training, GPU management, training logs, checkpointing)",
        "Model Registry & Versioning (model storage, version control, metadata management, model lineage, artifact management, model comparison)",
        "Model Deployment & Serving (REST/gRPC endpoints, A/B testing, canary deployments, rollback capability, auto-scaling, load balancing)",
        "Inference API (batch inference, real-time inference, request queuing, response caching, model ensemble, prediction logging)",
        "Monitoring & Observability (model drift detection, performance metrics, data quality monitoring, alerting, dashboards, anomaly detection)",
        "Dashboard & Visualization (experiment results, model comparison, metrics charts, resource utilization, cost tracking, project overview)",
        "Dataset Management (dataset versioning, labeling interface, data splits, annotation tools, dataset statistics, data augmentation)",
        "Cost & Usage Tracking (compute costs, API usage, resource allocation, budget alerts, usage reports, optimization recommendations)",
    ],

    "blockchain": [
        "Wallet Integration (MetaMask, WalletConnect, hardware wallets, multi-chain support, account abstraction, wallet recovery)",
        "Smart Contract Interaction (contract deployment, transaction signing, gas estimation, contract verification, event listening, ABI management)",
        "User Authentication (wallet-based auth, signature verification, session management, nonce handling, message signing, ENS support)",
        "Transaction Management (transaction history, status tracking, gas optimization, transaction simulation, batch transactions, pending queue)",
        "Token Management (ERC-20/721/1155 support, token transfers, balance queries, token approvals, token metadata, custom tokens)",
        "NFT Marketplace Features (listing, bidding, auction system, royalties, metadata display, collection management, lazy minting)",
        "DeFi Integration (token swaps, liquidity pools, staking, yield farming, lending/borrowing, portfolio tracking)",
        "Admin Dashboard (contract management, user analytics, transaction monitoring, treasury management, governance tools)",
        "Blockchain Explorer Integration (transaction lookup, address tracking, event logs, contract source, token holders, analytics)",
        "Security Features (signature validation, reentrancy protection, access controls, multi-sig support, timelock, pausable contracts)",
    ],

    "unknown": [
        "User Authentication & Authorization (OAuth2, JWT, role-based access, MFA, session management, password policies)",
        "Admin Dashboard (user management, content management, system analytics, configuration, audit logs)",
        "Database & Data Management (CRUD operations, data validation, migrations, backup/restore, data integrity)",
        "API Layer (RESTful endpoints, error handling, rate limiting, versioning, documentation, authentication)",
        "Search & Filtering (text search, filters, sorting, pagination, advanced search, search suggestions)",
        "Notification System (email notifications, in-app notifications, push notifications, preferences, templates)",
        "Settings & Configuration (application settings, user preferences, system configuration, feature flags)",
        "Logging & Monitoring (audit logs, error tracking, performance monitoring, analytics, alerting)",
    ],
}
